export const SET_PAGE_SIZE= "SET_PAGE_SIZE"
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER"
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS"
export const POST_MESSAGE_REQUEST = "POST_MESSAGE_REQUEST"
